refactor nv lists get

diff --git a/package/batocera/core/batocera-scripts/scripts/batocera-get-nvidia-list b/package/batocera/core/batocera-scripts/scripts/batocera-get-nvidia-list
--- a/package/batocera/core/batocera-scripts/scripts/batocera-get-nvidia-list
+++ b/package/batocera/core/batocera-scripts/scripts/batocera-get-nvidia-list
@@ -3,43 +3,64 @@
 # Bash script to get the latest Nvidia driver lists
 # which may add new boards in between versions.
 
-GITHUB_URL="https://raw.githubusercontent.com/batocera-linux/nvidia-lists/main/"
-DEST_DIR="/userdata/system/.nvidia"
 LOG_DIR="/userdata/system/logs"
 LOG_FILE="$LOG_DIR/nvidia.log"
+DEST_DIR="/userdata/system/.nvidia"
 
-# Create directories if they do not exist
-mkdir -p "$DEST_DIR"
-mkdir -p "$LOG_DIR"
+# Function to ensure the destination directory exists
+ensure_directory() {
+    mkdir -p "$1"
+}
 
-# Function to check internet connectivity using multiple methods
+# Function to check internet connectivity
 check_internet() {
-    if ping -q -w 1 -c 1 github.com > /dev/null || 
-       curl -s --max-time 2 -I http://github.com | grep -q "HTTP/[12].[01] [23].." ||
-       wget -q --spider http://github.com; then
+    # Method 1
+    if ping -c 1 1.1.1.1 &> /dev/null; then
         return 0
-    else
-        return 1
     fi
+    # Method 2
+    if curl -IsSf https://www.google.com >/dev/null; then
+        return 0
+    fi
+    return 1
 }
 
-# Function to download a file
+# Function to download files
 download_file() {
-    local filename=$1
-    wget -q --tries=5 --timeout=1 --no-check-certificate --no-cache --no-cookies -O "$DEST_DIR/$filename" "${GITHUB_URL}$filename" &&
-    echo "Download of $filename successful. File saved to $DEST_DIR/$filename" >> "$LOG_FILE"
+    curl -sSf "$1" -o "$2"
+    return $?
 }
 
-# Check for an internet connection
-if check_internet; then
-    echo "Internet connection detected, downloading Nvidia driver lists..." >> "$LOG_FILE"
-    
-    # Download lists in parallel
-    download_file "production.list" &
-    download_file "legacy390.list" &
-    download_file "legacy340.list" &
-    download_file "legacy.list" &
-    wait
+# Ensure log directories exist
+ensure_directory "$LOG_DIR"
+ensure_directory "$DEST_DIR"
+
+# Try to check for an internet connection up to 6 times, with a 5-second delay
+tries=6
+while [ $tries -gt 0 ]; do
+    if check_internet; then
+        echo "Internet connection detected, downloading Nvidia driver lists..." >> "$LOG_FILE"
+        break
+    else
+        sleep 5s
+        tries=$((tries - 1))
+    fi
+done
+
+# Check if the download was successful
+if [ $tries -gt 0 ]; then
+    # Array of files to download
+    files=("production.list" "legacy.list" "legacy390.list" "legacy340.list")
+
+    # Loop through the files and download them
+    for file in "${files[@]}"; do
+        download_file "https://raw.githubusercontent.com/batocera-linux/nvidia-lists/main/$file" "$DEST_DIR/$file"
+        if [ $? -eq 0 ]; then
+            echo "Download of $file successful. File saved to $DEST_DIR/$file" >> "$LOG_FILE"
+        else
+            echo "Download of $file failed." >> "$LOG_FILE"
+        fi
+    done
 else
-    echo "No internet connection detected, could not download Nvidia driver lists." >> "$LOG_FILE"
+    echo "Maximum retries reached. Could not establish an internet connection for the Nvidia driver lists" >> "$LOG_FILE"
 fi
