fix manual BT to pair using bluetoothctl

diff --git a/package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth b/package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
--- a/package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
+++ b/package/batocera/core/batocera-scripts/scripts/bluetooth/batocera-bluetooth
@@ -2,6 +2,8 @@
 
 ACTION=$1
 
+log=/userdata/system/logs/bluetooth.log
+
 do_help() {
     echo "${1} list" >&2
     echo "${1} trust <device address>" >&2
@@ -9,6 +11,9 @@ do_help() {
     echo "${1} remove <device address>" >&2
     echo "${1} save" >&2
     echo "${1} restore" >&2
+    echo "${1} pair_device <device address>" >&2
+    echo "${1} trust_device <device address>" >&2
+    echo "${1} connect_device <device address>" >&2
     echo "${1} start_live_devices" >&2
     echo "${1} stop_live_devices" >&2
 }
@@ -25,10 +30,8 @@ do_restore() {
 
 do_list() {
     find /var/lib/bluetooth/ -type f -name info |
-	while read FILE
-	do
-            if grep -qE '^Trusted=true$' "${FILE}"
-            then
+	while read FILE; do
+      if grep -qE '^Trusted=true$' "${FILE}"; then
 		DEVNAME=$(grep -E '^Name=' "${FILE}" | sed -e s+"^Name="++)
 		DEVCLASS=$(grep -E '^Class=' "${FILE}" | sed -e s+"^Class="++)
 		DEVADDR=$(basename $(dirname "${FILE}"))
@@ -37,7 +40,7 @@ do_list() {
 		test "${DEVCLASS}" = "0x002508" && DEVTYPE="joystick"
 		test "${DEVCLASS}" = "0x000508" && DEVTYPE="joystick"
 		echo "<device id=\""${DEVADDR}"\" name=\""${DEVNAME}"\" type=\""${DEVTYPE}"\" />"
-	    fi
+	  fi
 	done
 }
 
@@ -91,14 +94,39 @@ do_trust() {
     touch "/var/run/bt_status" || retrun 1
     LAST_MSG=$(cat "/var/run/bt_status")
 
-    # check input
-    if test "${TRUSTDEV}" != "input"
-    then
-	# trust device
-	if ! echo "${TRUSTDEV}" | grep -qE "^([0-9A-F]{2}:){5}[0-9A-F]{2}$"
-	then
-	    return 1
-	fi
+	# trust device based on mac address
+    if test "${TRUSTDEV}" != "input"; then
+      # check for a valid mac address
+      if echo ${TRUSTDEV} | grep -q -E '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'; then
+        # pair the device
+        echo "Attempting to setup bluetooth device ${TRUSTDEV}" > $log
+        echo "" >> $log
+        do_pair_device "$TRUSTDEV" 2> /dev/null
+        if [ $? -ne 0 ]; then
+          echo "Error: Pairing device $TRUSTDEV failed." >> $log
+          exit 1
+        else
+          echo "Device ${TRUSTDEV} paired successfully." >> $log
+        fi
+        # now trust the device
+        do_trust_device "$TRUSTDEV" 2> /dev/null
+        if [ $? -ne 0 ]; then
+          echo "Error: Trusting $TRUSTDEV failed." >> $log
+          exit 1
+        else
+          echo "Device ${TRUSTDEV} trusted successfully." >> $log
+        fi
+        # now connect the device (usually not necessary)
+        do_connect_device "$TRUSTDEV" 2> /dev/null
+        if [ $? -ne 0 ]; then
+          echo "Error: Connecting $TRUSTDEV failed." >> $log
+          exit 1
+        else
+          echo "Device ${TRUSTDEV} connected successfully." >> $log
+        fi
+      else
+        echo "Invalid MAC address" >> $log
+      fi
     fi
     echo "${TRUSTDEV}" > /var/run/bt_device || return 1
 
@@ -147,6 +175,87 @@ do_trust() {
     do_save # save
 }
 
+do_trust_device() {
+  if [ -z "$1" ]; then
+    echo "Please provide a device name or address"
+    return 1
+  fi
+
+  device_info=$(bluetoothctl info "$1")
+  if [ $? -ne 0 ]; then
+    echo "Error: Device $1 not found" >> $log
+    return 1
+  fi
+
+  if ! echo "$device_info" | grep -q "Trusted: yes"; then
+    echo "Trusting device $1..." >> $log
+    bluetoothctl trust "$1"
+  else
+    echo "Device $1 is already trusted" >> $log
+  fi
+}
+
+do_pair_device() {
+  if [ -z "$1" ]; then
+    echo "Please provide a device name or address"
+    return 1
+  fi
+
+  device_info=$(bluetoothctl info "$1")
+  if [ $? -ne 0 ]; then
+    echo "Error: Device $1 not found" >> $log
+    return 1
+  fi
+
+  if ! echo "$device_info" | grep -q "Paired: yes"; then
+    echo "Pairing with device $1..." >> $log
+    bluetoothctl pair "$1"
+  else
+    echo "Device $1 is already paired" >> $log
+  fi
+}
+
+do_connect_device() {
+  if [ -z "$1" ]; then
+    echo "Please provide a device name or address"
+    return 1
+  fi
+
+  device_info=$(bluetoothctl info "$1")
+  if [ $? -ne 0 ]; then
+    echo "Error: Device $1 not found" >> $log
+    return 1
+  fi
+
+  if ! echo "$device_info" | grep -q "Connected: yes"; then
+    echo "Connecting to device $1..." >> $log
+    bluetoothctl connect "$1"
+  else
+    echo "Device $1 is already connected" >> $log
+  fi
+}
+
+do_is_gaming() {
+  if [ -z "$1" ]; then
+    echo "Please provide a device name or address"
+    return 1
+  fi
+
+  device_info=$(bluetoothctl info "$1")
+  if [ $? -ne 0 ]; then
+    echo "Error: Device $1 not found" >> $log
+    return 1
+  fi
+
+  if echo "$device_info" | grep -q "Icon: input-gaming"; then
+    echo "Device is an input-gaming type" >> $log
+    return 0
+  else
+    echo "Device in not an input-gaming type" >> $log
+    return 1
+  fi
+}
+
 case "${ACTION}" in
     "list")
 	do_list
@@ -170,6 +279,18 @@ case "${ACTION}" in
     "restore")
 	do_restore
 	;;
+    "pair_device")
+    do_pair_device
+    ;;
+    "trust_device")
+    do_trust_device
+    ;;
+    "connect_device")
+    do_connect_device
+    ;;
+    "is_gaming")
+    do_is_gaming
+    ;;
     "start_live_devices"|"live_devices")
 	do_devlist
 	;;
