OMX changed

diff --git a/package/batocera/core/batocera-splash/S03splash-omx b/package/batocera/core/batocera-splash/S03splash-omx
--- a/package/batocera/core/batocera-splash/S03splash-omx
+++ b/package/batocera/core/batocera-splash/S03splash-omx
@@ -33,20 +33,20 @@ do_imagestart()
 do_videostart ()
 {
     video="$1"
-    # Initialize dbus session
-    OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.root"
-    OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.root.pid"
-    exec 5> "$OMXPLAYER_DBUS_ADDR"
-    exec 6> "$OMXPLAYER_DBUS_PID"
-    dbus-daemon --fork --print-address 5 --print-pid 6 --session
-    until [ -s "$OMXPLAYER_DBUS_ADDR" ]; do
-        echo "waiting for dbus address to appear" >&2
-        sleep .2
-    done
-    DBUS_SESSION_BUS_ADDRESS=`cat $OMXPLAYER_DBUS_ADDR`
-    DBUS_SESSION_BUS_PID=`cat $OMXPLAYER_DBUS_PID`
-    export DBUS_SESSION_BUS_ADDRESS
-    export DBUS_SESSION_BUS_PID
+    # Initialize dbus session ----- WE DO not need imho
+#    OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.root"
+#    OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.root.pid"
+#    exec 5> "$OMXPLAYER_DBUS_ADDR"
+#    exec 6> "$OMXPLAYER_DBUS_PID"
+#    dbus-daemon --fork --print-address 5 --print-pid 6 --session
+#    until [ -s "$OMXPLAYER_DBUS_ADDR" ]; do
+#        echo "waiting for dbus address to appear" >&2
+#        sleep .2
+#    done
+#    DBUS_SESSION_BUS_ADDRESS=`cat $OMXPLAYER_DBUS_ADDR`
+#    DBUS_SESSION_BUS_PID=`cat $OMXPLAYER_DBUS_PID`
+#    export DBUS_SESSION_BUS_ADDRESS
+#    export DBUS_SESSION_BUS_PID
 
     # Launch the video
     omx_fnt="--font=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf"
@@ -62,38 +62,27 @@ do_videostart ()
     # -911 = Volume set to 35% (On omxplayer)
     # 1/(10^(911/2000)) = 0.35034828830157
 
+    # Later we remove the volume ... the user/video creator is responsible for audio volume
     /usr/bin/omxplayer -o both --vol -2500 $omx_opt $omx_srt $omx_nosound "$video" &
-    PID=$!
-
-    # Stop the video when ready
-    if [[ $? -eq 0 ]]; then
-        # Wait for emulationstation or Kodi, but not more than 20 seconds
-        count=0
-        while [[ ! -f "/tmp/emulationstation.ready" && ! -e "/var/run/kodi.msg" && $count -lt 400 ]]; do
-            sleep 0.1
-            ((count++))
-        done
-        # Finish with a one second fade out.
-        audio_fade=1
-        video_fade=250
-        while [[ $video_fade -gt 0 ]]; do
-            sleep .02
-            dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Volume double:$audio_fade >/dev/null
-            dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.SetAlpha objpath:/not/used int64:$video_fade >/dev/null
-            audio_fade=`echo "$audio_fade .02" | awk '{printf "%.2f", $1-$2}'`
-            ((video_fade=video_fade-5))
-        done
-        # Ready flag set or timeout occured; stop video process.
-        dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Action int32:15 >/dev/null
-    fi
+    
+    # Here we create the videoplay.pid --- we should do the same for picture (just to divide if a picture was loaded with success)
+    PID=$! 
+    echo $PID > /tmp/videoplayer.pid
+    wait $PID
+    rm -f /tmp/videoplayer.pid
 }
+
 
 case "$1" in
     start)
 	grep -qE '^[ ]*autoresize[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" && exit 0
+	#We use that later to disable splash at all
+        #grep -qE '^[ ]*bootsplash[ ]*=[ ]*true[ ]*$' "/boot/batocera-boot.conf" || exit 0
         do_start &
         ;;
     stop)
+        echo "Executing /etc/init/S29abortsplash"
+        /etc/init.d/S29abortsplash stop
         ;;
     restart|reload)
         ;;
